//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterAngler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class KeyBindings : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyBindings defaultInstance = ((KeyBindings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyBindings())));
        
        public static KeyBindings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys Interact {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Interact"]));
            }
            set {
                this["Interact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys CastFishing {
            get {
                return ((global::System.Windows.Forms.Keys)(this["CastFishing"]));
            }
            set {
                this["CastFishing"] = value;
            }
        }
    }
}
